name: learning docker
on:
  push:
    branch:
      - testing-pipeline
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout our repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: action/setup-node@v1
        with:
          node-version: "14"

      - name: Build the Docker Image :)
        run: docker build -t akamprogramist/front-web-store-lab4:akamprogramist/front-web-store-lab4 .

      - name: Log in to the Docker hub :>
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}

      - name: Push the docker to dockerhub ;)
        run: docker push akamprogramist/front-web-store-lab4:akamprogramist/front-web-store-lab4 .
